[build]
  publish = ".next"
  command = "npm run build"

[[redirects]]
  from = "https://misinfo-dashboard.netlify.app/*"
  to = "https://truthsleuthlocal.netlify.app/:splat"
  status = 301
  force = true
